apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-mysql
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    component: mysql
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.mysql.port }}
    targetPort: mysql
    protocol: TCP
    name: mysql
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
    component: mysql
