apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-nginx
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    component: nginx
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
    component: nginx
