apiVersion: v2
name: monitoring
description: Prometheus and Grafana monitoring stack
type: application
version: 1.0.0
appVersion: "latest"
dependencies:
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: "7.0.0"
    repository: "https://grafana.github.io/helm-charts"
