apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: default
data:
  alert-rules.yml: |
    groups:
    - name: wordpress_alerts
      interval: 30s
      rules:
      - alert: HighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total{namespace="default",pod=~".*wordpress.*"}[5m])) by (pod) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.pod }}"
          description: "Pod {{ $labels.pod }} has CPU usage above 80% (current value: {{ $value }}%)"
      
      - alert: HighMemoryUsage
        expr: sum(container_memory_usage_bytes{namespace="default",pod=~".*wordpress.*"}) by (pod) / sum(container_spec_memory_limit_bytes{namespace="default",pod=~".*wordpress.*"}) by (pod) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.pod }}"
          description: "Pod {{ $labels.pod }} has memory usage above 80% (current value: {{ $value }}%)"
      
      - alert: High5xxErrorRate
        expr: sum(rate(nginx_http_requests_total{status=~"5.."}[5m])) / sum(rate(nginx_http_requests_total[5m])) * 100 > 5
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High 5xx error rate detected"
          description: "5xx error rate is above 5% (current value: {{ $value }}%)"
      
      - alert: PodDown
        expr: up{job="kubernetes-pods"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Pod {{ $labels.kubernetes_pod_name }} is down"
          description: "Pod {{ $labels.kubernetes_pod_name }} in namespace {{ $labels.kubernetes_namespace }} has been down for more than 1 minute"
      
      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, sum(rate(nginx_http_request_duration_seconds_bucket[5m])) by (le)) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High request latency detected"
          description: "95th percentile request latency is above 1 second (current value: {{ $value }}s)"
      
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk space is below 10% on {{ $labels.instance }} (current value: {{ $value }}%)"
